### ISSUE TITLE
SOAP UI 5.4.0 :Getting error while configuring listeners

### ISSUE THREAD

**Issue by somesh-dimber** [reportportal/agent-java-soapui#7]
Hi ,
I am using SOAPUI 5.4.0 and added SOAP UI binaries on git to respective folders as per documentation.
And I started SOAP UI 5.4.0 again and I have found that listeners are not added.

I am only able to see:
Thu Jan 24 15:42:08 IST 2019:INFO:Adding listeners from [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\listeners\agent-java-soapui-master\soapui\src\main\resources\reportportal-listeners.xml]
Please refer to SOAP logs for more details.

Best Regards,
Somesh

Logs:
```
Thu Jan 24 15:42:06 IST 2019:INFO:Adding [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\ext\gradle-wrapper.jar] to extensions classpath
Thu Jan 24 15:42:06 IST 2019:INFO:Adding [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\ext\postgresql-42.2.5.jre6.jar] to extensions classpath
Thu Jan 24 15:42:06 IST 2019:INFO:initialized soapui-settings from [C:\Users\XXX\soapui-settings.xml]
Thu Jan 24 15:42:08 IST 2019:INFO:Adding listeners from [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\listeners\agent-java-soapui-master\soapui\src\main\resources\reportportal-listeners.xml]
Thu Jan 24 15:42:09 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\readyapi-postman-1.0.1.jar]
Thu Jan 24 15:42:09 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\ready-uxm-plugin-1.0.1-dist.jar]
Thu Jan 24 15:42:10 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Thu Jan 24 15:42:10 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
Thu Jan 24 15:42:10 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\soapui-swagger-plugin-2.2-dist.jar]
Thu Jan 24 15:42:10 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Added AutoFactory for [PluginPrefs]
Thu Jan 24 15:42:10 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
Thu Jan 24 15:42:10 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\ready-mqtt-plugin-dist.jar]
Added AutoFactory for [PluginTestStep]
Added AutoFactory for [PluginTestStep]
Added AutoFactory for [PluginTestStep]
Thu Jan 24 15:42:11 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Added AutoFactory for [PluginPanelBuilder]
Added AutoFactory for [PluginPanelBuilder]
Added AutoFactory for [PluginPanelBuilder]
Thu Jan 24 15:42:11 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
Thu Jan 24 15:42:11 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Thu Jan 24 15:42:11 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
Thu Jan 24 15:42:11 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\readyapi-swaggerhub-plugin-1.0.jar]
Thu Jan 24 15:42:11 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Thu Jan 24 15:42:11 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
Thu Jan 24 15:42:11 IST 2019:INFO:5 plugins loaded in 2082 ms
Thu Jan 24 15:42:11 IST 2019:INFO:All plugins loaded
Thu Jan 24 15:42:11 IST 2019:INFO:Adding [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\ext\gradle-wrapper.jar] to extensions classpath
Thu Jan 24 15:42:11 IST 2019:INFO:Adding [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\ext\postgresql-42.2.5.jre6.jar] to extensions classpath
Thu Jan 24 15:42:11 IST 2019:INFO:initialized soapui-settings from [C:\Users\XXX\soapui-settings.xml]
Thu Jan 24 15:42:11 IST 2019:INFO:Adding listeners from [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\listeners\agent-java-soapui-master\soapui\src\main\resources\reportportal-listeners.xml]
Thu Jan 24 15:42:12 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\readyapi-postman-1.0.1.jar]
Thu Jan 24 15:42:12 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\ready-uxm-plugin-1.0.1-dist.jar]
Thu Jan 24 15:42:13 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Thu Jan 24 15:42:13 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
Thu Jan 24 15:42:13 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\soapui-swagger-plugin-2.2-dist.jar]
Thu Jan 24 15:42:13 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Added AutoFactory for [PluginPrefs]
Thu Jan 24 15:42:13 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
Thu Jan 24 15:42:13 IST 2019:INFO:Adding plugin from [C:\Users\XXX\.soapuios\plugins\ready-mqtt-plugin-dist.jar]
Added AutoFactory for [PluginTestStep]
Added AutoFactory for [PluginTestStep]
Added AutoFactory for [PluginTestStep]
Thu Jan 24 15:42:13 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Added AutoFactory for [PluginPanelBuilder]
Added AutoFactory for [PluginPanelBuilder]
Added AutoFactory for [PluginPanelBuilder]
Thu Jan 24 15:42:13 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
Thu Jan 24 15:42:13 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoDiscoveryMethodFactory], see error log for details
Thu Jan 24 15:42:13 IST 2019:ERROR:An error occurred [com.eviware.soapui.plugins.auto.factories.AutoImportMethodFactory], see error log for details
```

**Comment by somesh-dimber** [comment]
Some More logs:
Thu Jan 24 17:38:20 IST 2019:INFO:directory: C:\Program Files\SmartBear\SoapUI-5.4.0\bin\.

Thu Jan 24 17:38:20 IST 2019:INFO:command: cmd.exe /C testrunner.bat -sReport_PORTAL_RegTestSuite_DOM_CS -cENV_CA -r -a -j -J -fC:\Results\DOM_content_service_smoke\Regression\33\GETALL -S C:\Users\XXXx\Documents\SOAP_projects_local\MasterTestSuite-SmokeTestSuite-soapui-project_or.xml

Thu Jan 24 17:38:20 IST 2019:INFO:SoapUI 5.4.0 TestCase Runner
Configuring log4j from [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\soapui-log4j.xml]

Thu Jan 24 17:38:21 IST 2019:INFO:17:38:21,093 INFO  [SoapUI] Adding [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\ext\gradle-wrapper.jar] to extensions classpath
17:38:21,094 INFO  [SoapUI] Adding [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\ext\postgresql-42.2.5.jre6.jar] to extensions classpath

Thu Jan 24 17:38:21 IST 2019:INFO:log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: global-groovy.log (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
	at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:345)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:827)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:604)
	at org.apache.log4j.xml.XMLWatchdog.doOnChange(DOMConfigurator.java:861)
	at org.apache.log4j.helpers.FileWatchdog.checkAndConfigure(FileWatchdog.java:88)
	at org.apache.log4j.helpers.FileWatchdog.<init>(FileWatchdog.java:57)
	at org.apache.log4j.xml.XMLWatchdog.<init>(DOMConfigurator.java:853)
	at org.apache.log4j.xml.DOMConfigurator.configureAndWatch(DOMConfigurator.java:584)
	at com.eviware.soapui.DefaultSoapUICore.initLog(DefaultSoapUICore.java:492)
	at com.eviware.soapui.DefaultSoapUICore.init(DefaultSoapUICore.java:136)
	at com.eviware.soapui.DefaultSoapUICore.<init>(DefaultSoapUICore.java:132)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.createSoapUICore(AbstractSoapUIRunner.java:216)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.run(AbstractSoapUIRunner.java:192)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.run(AbstractSoapUIRunner.java:137)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.runFromCommandLine(AbstractSoapUIRunner.java:112)
	at com.eviware.soapui.tools.SoapUITestCaseRunner.main(SoapUITestCaseRunner.java:122)

Thu Jan 24 17:38:21 IST 2019:INFO:17:38:21,335 INFO  [DefaultSoapUICore] initialized soapui-settings from [C:\Users\XXXx\soapui-settings.xml]

Thu Jan 24 17:38:22 IST 2019:INFO:17:38:22,860 INFO  [DefaultSoapUICore] Adding listeners from [C:\Program Files\SmartBear\SoapUI-5.4.0\bin\listeners\agent-java-soapui-master\soapui\src\main\resources\reportportal-listeners.xml]

Thu Jan 24 17:38:22 IST 2019:INFO:Error initializing Listener: java.lang.ClassNotFoundException: com.epam.reportportal.soapui.listeners.RPTestRunListener
Error initializing Listener: java.lang.ClassNotFoundException: com.epam.reportportal.soapui.listeners.RPTestSuiteRunListener
Error initializing Listener: java.lang.ClassNotFoundException: com.epam.reportportal.soapui.listeners.RPProjectRunListener

**Comment by DzmitryHumianiuk** [comment]
@somesh-dimber did you manage to resolve it?

**Comment by somesh-dimber** [comment]
Hi Dzmitry,

Thanks for reply.

Issue got resolved I had recompiled from source again and also there were few configuration problems with SOAP UI.

It is working great!!!

Hope we can also have support for Python and Jmeter.
Nevertheless this is great tool to have in Test Automation and I hope it will become standard one day. 

Best Regards,
Somesh
